### ISSUE TITLE
aui:fieldset-group is no more supported since LP7.4GA54

### ISSUE THREAD

**Issue by ccariou** [ONLYOFFICE/onlyoffice-liferay#40]
Hi,
"aui:fieldset-group" taglib element is used in create.jsp (at least), but this element is no more present in liferay aui taglib (>=GA54).

Instead you should use : 
`<div class="sheet"><div class="panel-group panel-group-flush">`

[exemple](https://github.com/liferay/liferay-portal/commit/e1a1cdeebbc9ecfe1e6bc2edd863a546b145ed3d)

**Comment by aleksandrfedorov97** [comment]
fixed (https://github.com/ONLYOFFICE/onlyoffice-liferay/commit/b5fba796a614bfdd43d767423c6f7dc7ddf2aa5f)
